### ISSUE TITLE
extention dos not compile for php 7.3.2 details follows

### ISSUE THREAD

**Issue by EGYPHARAOH** [OOPS-ORG-PHP/ncurses#1]
Hello and thank you in advance for this mod_ncurses
it does not compile and here what is going on but first here the compilation env:
VS2017 build tools
$ phpsdk_version
PHP SDK 2.2.0-dev
PDcurses built with:-
nmake -f Makefile.vc DEBUG=Y WIDE=Y UTF8=Y  all
build errors starts with this line:
pecl\ncurses-1.0.2\ncurses_functions.c(1284): warning C4013: 'putp' undefined; assuming extern returning int
THEN near the end:
Creating library D:\php-sdk2\phpmaster\vc15\x64\php-7.3.2-src\x64\Release_TS\php_ncurses.lib and object D:\php-sdk2\phpmaster\vc15\x64\php-7.3.2-src\x64\Release_TS\php_ncurses.exp
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
ncurses_functions.obj : error LNK2019: unresolved external symbol vidattr referenced in function zif_ncurses_vidattr@@16
ncurses_functions.obj : error LNK2019: unresolved external symbol putp referenced in function zif_ncurses_putp@@16
D:\php-sdk2\phpmaster\vc15\x64\php-7.3.2-src\x64\Release_TS\php_ncurses.dll : fatal error LNK1120: 2 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe"' : return code '0x460'
Stop.
WHAT am I doing wrong?
[mod_ncurses compile_session with errors.txt](https://github.com/OOPS-ORG-PHP/mod_ncurses/files/2970732/mod_ncurses.compile_session.with.errors.txt)

**Comment by Joungkyun** [comment]
First, the ___'putp' undefined___ issue is not related to a build failure.

```make
pecl\ncurses-1.0.2\ncurses_functions.c(1284): warning C4013: 'putp' undefined; assuming extern returning int
```
This message is just a warning.

The actual build failure is occurring in the link step.
```make
Creating library D:\php-sdk2\phpmaster\vc15\x64\php-7.3.2-src\x64\Release_TS\php_ncurses.lib and object D:\php-sdk2\phpmaster\vc15\x64\php-7.3.2-src\x64\Release_TS\php_ncurses.exp
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
ncurses_functions.obj : error LNK2019: unresolved external symbol vidattr referenced in function zif_ncurses_vidattr@@16
ncurses_functions.obj : error LNK2019: unresolved external symbol putp referenced in function zif_ncurses_putp@@16
D:\php-sdk2\phpmaster\vc15\x64\php-7.3.2-src\x64\Release_TS\php_ncurses.dll : fatal error LNK1120: 2 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe"' : return code '0x460'
```

In the above message, VS2017 can not link to vidattr api and putp api in the pdcurses library. From ths message, there seems to be a problem that VS can't link vidattr and putp apis  in the current pdcurses library. (For example, if the APIs is removed from the current version)

First, I do not have experience building on windows. So I guess by the error message and give advice.

It is a good idea to check that your pdcurses library supports vidattr and putp api.

**Comment by EGYPHARAOH** [comment]
Which version did you used when u did the mod?
I'm not that much of a programmer myself, I barely follow the instructions for getting what I miss.
Why pdcurses and not the ncurses on windows is another in my mind

**Comment by Joungkyun** [comment]
@EGYPHARAOH I have not used PHP in the windwos yet, so it is similar to yours. 
However, by searching, can not use ncurses on windows, so it seems to use pdcurses.

https://stackoverflow.com/questions/138153/is-ncurses-available-for-windows

I am not the one who created mod_ncurses. I'm doing maintenance on mod_ncurses in PHP 7 on Linux. So I can not help build with windwos.

My maintenance environment is CentOS 6/7 ncurses (5.7 / 5.9).

**Comment by EGYPHARAOH** [comment]
Ok sir
I have done it and got the php_ncurses.dll extension compiled and working
Here is the story for whom ever may need to walk the same path:
1- NOTHING wrong in mod_ncurses and it does not need any modifications to work with PHP7.3.2, it comiles out of the box and any problems comes from the library PDcurses.lib
2- there are 2 version out there for PDCurses:-
    2-a) wmcbrine/PDCurses ( https://github.com/wmcbrine/PDCurses ) "DON'T USE IT, will not work with this mod_ncurses"
    2-b) Bill-Gray/PDCurses ( https://github.com/Bill-Gray/PDCurses ) "USE THIS, it is the only thing worked"
3- that PDcurses uses cmake for generating the .vcxproj and hence I am not a pro programmer i used cmake desktop edition and follows the configurations that worked with me:
 cmake_build_type=RelwithDebinfo
PDCDEBUG=OFF
PDC_CHTYPE_16=ON
PDC_CHTYPE_32=ON
PDC_UTF8=ON
PDC_WIDE=ON
Turn off the rest specially shared,dos and sdl
press configure, press generate then on cmd >msbuild ALL_BUILD.vcxproj
>msbuild install.vcxproj

now u will have at "c:\programs files (x86)\pdcurses" 2 folders use "wincon" the other "wingui" complains about missing external definitions even it makes more sense than "wincon" 
4-copy pdcursesstatic.lib to your deps\lib\pdcurses.lib
5-copy the 3 header files "curses.h" "term.h" and "panel.h" to your deps\include
6- now u go all the usual way:
>nmake clean-all
>buildconf --force
>configure --help (to be sure that now you have --with-ncurses
>configure --disable-all -enable-cgi --with-ncurses=shared
etc etc
I have attached here the pdcurses.lib and the incs needed that I have built
and also the php_ncurses.dll the extention that I have built
Thank you for your reply and effort
NOTE: pdcurses.lib been built for the x64 arch under win10 with vs2017
php_ncurses has been built for php-7.3.2 thread safe x64 with vs2017
both works and tested

[pdcurses_lib.zip](https://github.com/OOPS-ORG-PHP/mod_ncurses/files/2975116/pdcurses_lib.zip)
[php_ncurses.zip](https://github.com/OOPS-ORG-PHP/mod_ncurses/files/2975117/php_ncurses.zip)

**Comment by Joungkyun** [comment]
Yes. The version maintained by William McBrine (latest version 3.8/2019) is caused by the lack of putp and vidattr api.

```bash
[papa@Boss PDCurses-3.8]$ grep -Pr "putp|vidattr"
curses.h:PDCEX  int     vidattr(chtype);
man/HISTORY.md:  scr_set(), use_env(), vidattr(), vidputs().
```

Perhaps Bill Gray has forked on this issue. (latest version 4.0.2/2017)

```bash
[papa@Boss PDCurses-4.0.2]$ grep -Pr "putp|vidattr"
curses.h:PDCEX int     vidattr(chtype);
HISTORY.md:  scr_set(), use_env(), vidattr(), vidputs().
pdcurses/terminfo.c:    int vidattr(chtype attr);
pdcurses/terminfo.c:    int putp(const char *);
pdcurses/terminfo.c:int vidattr(chtype attr)
pdcurses/terminfo.c:    PDC_LOG(("vidattr() - called: attr %d\n", attr));
pdcurses/terminfo.c:int putp(const char *str)
pdcurses/terminfo.c:    PDC_LOG(("putp() - called: str %s\n", str));
term.h:int     putp(const char *);
```
